### ISSUE TITLE
Versioning: Version field of ASP.NET Core project not updated, instead a new one is created

### ISSUE THREAD

**Issue by POFerro** [rfennell/AzurePipelines#598] opened 2020-01-08 15:27 UTC
### Azure DevOps Extension you are using
Versioning: VersionDotNetCoreAssembliesTask

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.23.5

### Expected behaviour and actual behaviour
Given this project file:
`&lt;?xml version="1.0" encoding="utf-8"?>
&lt;Project Sdk="Microsoft.NET.Sdk.Web">

  &lt;PropertyGroup Label="Globals">
    &lt;SccProjectName>SAK&lt;/SccProjectName>
    &lt;SccProvider>SAK&lt;/SccProvider>
    &lt;SccAuxPath>SAK&lt;/SccAuxPath>
    &lt;SccLocalPath>SAK&lt;/SccLocalPath>
    &lt;Platforms>AnyCPU;x64;x86&lt;/Platforms>
  &lt;/PropertyGroup>
  
  &lt;PropertyGroup>
    &lt;AspNetCoreModuleName>AspNetCoreModule&lt;/AspNetCoreModuleName>
  &lt;/PropertyGroup>
  
  &lt;PropertyGroup>
    &lt;Version>2.1.1.67&lt;/Version>
    &lt;EnableDefaultContentItems>true&lt;/EnableDefaultContentItems>
    &lt;TargetFramework>net461&lt;/TargetFramework>
  &lt;/PropertyGroup>
`
I was expecting to see Version field updated, instead a new Version field is created in the above PropertyGroup, this is the outputed version:
`&lt;PropertyGroup>
    &lt;AspNetCoreModuleName>AspNetCoreModule&lt;/AspNetCoreModuleName>
  &lt;Version>2.7.1.44&lt;/Version>&lt;/PropertyGroup>
`
Here are the logs of the execution:

Task         : Version .NET Core Assemblies
Description  : Applies a version to a .NET Core assembly via the .csproj files based on the build number. Based on Microsoft sample from https://msdn.microsoft.com/Library/vs/alm/Build/overview
Version      : 2.23.5
Author       : Black Marble
Help         : Version: 2.23.5. [More Information](https://github.com/rfennell/vNextBuild/wiki/Version-Assemblies-and-Packages-Tasks/)

Source Directory:  xxxxx
Filename Pattern: .csproj
Version Number/Build Number: 2.7.1.44
Version Filter to extract build number: \d+\.\d+\.\d+\.\d+
Field to update (all if empty): Version
Add default field (all if empty): false
Output: Version Number Parameter Name: OutputedVersion
Inject Version: false
SDK names: Microsoft.NET.Sdk
Extracting version number from build number
Extracted Version: 2.7.1.44
Matched the file 'xxxxxx.csproj' using the SDK name 'Microsoft.NET.Sdk'
Adding file xxxxxxx.csproj as is a .NETCore Project
Will apply 2.7.1.44 to 1 files.
Getting just the PropertyGroup that contains the single version fields
Found <PropertyGroup> block
The <Version> version is not present in the file so adding it
Cannot find a <TargetFramework> block, so just adding the version field at the end of the first <PropertyGroup>
xxxxxxxxxxxxxx.csproj - version applied
Set the output variable 'OutputedVersion' with the value 2.7.1.44

### Steps to reproduce the problem
Just execute with the above project file.

Thanks in advance and best regards
POFerro

**Comment by rfennell** [comment] 2020-01-08 15:49
I will have a look into that. The logic for finding existing tags is not as good as it should be, so I guess the problem is in there.

**Comment by rfennell** [comment] 2020-01-08 17:13
Got a repo in a unit test, will get it sorted

**Comment by rfennell** [comment] 2020-01-09 09:56
@POFerro  Thanks for proving the sample that caused the issue. Reporting issues like this really makes it easy to get a repo and hence solve the problem  

The fix has been released in 2.24.3, if it is not right re-open the issue.

**Closed by rfennell** 2020-01-09 09:56 UTC
Labels: Versioning

**Comment by POFerro** [comment] 2020-01-09 13:06
Hi @rfennell ,
Thanks for your quick answer, worked perfectly, glad to help finding the issue :).
Best regards
