### ISSUE TITLE
GenerateReleaseNotes(XPlatform) - Cannot read property '' of undefined

### ISSUE THREAD

**Issue by flasherwrasse** [rfennell/AzurePipelines#701] opened 2020-04-29 20:50 UTC
Our template was working until right around 4/5 and it looks like this started with an update as we had no changes on our side during the time we encountered this problem. I have made some changes to the template and other settings but still get this every time.

![image](https://user-images.githubusercontent.com/61990998/80645671-70e44b00-8a39-11ea-83cb-edd482fb6d67.png)

### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*

### Where are you running it?
*You can run the extensions in the cloud or on-premise*
- Azure DevOps Service (VSTS)
- Azure DevOps Server (on-premise TFS, if so what version)

### Version of Extension/Task
*I assume it is the currently public version, if you are using an older version on-premises let me know, but the answer will probably involve upgrading to the currently public version*

**Comment by rfennell** [comment] 2020-04-30 08:32
I have been struggling with another related issue #694. In both cases the problem is that a built in variable don't contain what the code expects, being GUID when Numbers are expected or undefined.

There are two possible reasons for this
- My fix for #694 introduced the issue the issue - most likely
- A change of behaviour in the agent or API - I am not using the latest version of one API, this is going to be upgraded, but introduced some changes so is non trival.

So for now, I have added a Try/Catch around the problematic logic. This should at least allow you to work as before. 

What is currently an error should be logged as warning, so could I ask you try running a release with the variable `system.debug=true` so we get the debug logs they help to see what is going on and create a better solution

This updated version is 2.41.1

**Comment by rfennell** [comment] 2020-05-05 13:23
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Closed by rfennell** 2020-05-05 13:23 UTC
Labels: GenerateReleaseNotes (XPlat version), bug
