### ISSUE TITLE
Error with ProjectId executing release notes task

### ISSUE THREAD

**Issue by h2ag11** [rfennell/AzurePipelines#655] opened 2020-03-31 07:01 UTC
### Azure DevOps Extension you are using
Generate Release Notes (Crossplatform)
in Azure devops server

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
2.30.5

### Expected behaviour and actual behaviour
Release notes should be generated. I use the next template:

> # Release notes
> ## Notes for release definition:  ${releaseDetails.releaseDefinition.name}
> **Release Number**  : ${releaseDetails.name}
> **Release completed** : ${releaseDetails.modifiedOn}
> **Compared Release Number**  : ${compareReleaseDetails.name}
> ### All associated work items
> @@WILOOP@@
> * ** ${widetail.fields['System.WorkItemType']} ${widetail.id} ** ${widetail.fields['System.Title']}
> @@WILOOP@@
> ### Associated commits
> @@CSLOOP@@
> * **ID ${csdetail.id} ** ${csdetail.message}
> @@CSLOOP@@

Until friday 27th RN were generated successfully. However, since 27th, I find following error executing the task:

> 2020-03-30T06:56:19.6106454Z Sorting WI by type then id
> 2020-03-30T06:56:19.6927580Z ##[error]Error: The guid specified for parameter projectId must not be Guid.Empty.
> Parameter name: projectId
> 2020-03-30T06:56:19.7032521Z ##[error]Error: The guid specified for parameter projectId must not be Guid.Empty.
> Parameter name: projectId

Perhaps it is due to an update in devops

**Comment by rfennell** [comment] 2020-03-31 08:05
My last release was the 21st, so I don't think the issue is due to a change I have made.

I cannot immediately get a repo but I will continue to look

**Comment by rfennell** [comment] 2020-03-31 09:05
This is a strange one. I have no variable called `projectid` and assuming that the line this is failing is the sort all this does is sort on the type then id

```
        fullWorkItems = fullWorkItems.sort((a, b) => (a.fields["System.WorkItemType"] > b.fields["System.WorkItemType"]) ? 1 : (a.fields["System.WorkItemType"] === b.fields["System.WorkItemType"]) ? ((a.id > b.id) ? 1 : -1) : -1 );
        
```

I would expect the next line in the log to be (assuming you have debugging on)

```
2020-03-31T08:46:33.4827519Z Sorting WI by type then id
2020-03-31T08:46:33.4828955Z ##[debug]Build.BuildId=4628
2020-03-31T08:46:33.6915739Z ##[debug]Using template mode InLine
2020-03-31T08:46:33.6916621Z Using in-line template
```
Have you tried changing the sort option to see if the problem still occurs. I want to isolate if it is a sort issue or a template processing issue

**Comment by rfennell** [comment] 2020-04-15 10:39
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Closed by rfennell** 2020-04-15 10:39 UTC
Labels: GenerateReleaseNotes (XPlat version)

**Comment by rfennell** [comment] 2020-04-28 15:47
See #694
