### ISSUE TITLE
Mono Repo Support

### ISSUE THREAD

**Issue by faheemgani** [rfennell/AzurePipelines#1568] opened 2023-11-24 17:55 UTC
### Azure DevOps Extensions

Artifact PR Description

### Is your feature request related to a problem? Please describe.

We are currently using a mono-repo, where the folder structure looks something like this:

-build/basket/deploy.yml
-build/product/deploy.yml 
-build/booking/deploy.yml
-src/services/basket/
-src/services/product/
-src/services/booking/
-tests/services/basket/unit/
-tests/services/product/unit/
-tests/services/booking/unit/

Each service has it's own pipeline but all the pipelines sit within the same repository.

I have successfully implemented the extension into my pipelines, the template we are using is below:

            # Release Notes: {{buildDetails.definition.name}} 
                    
            {{#if (gt workItems.length 0)}}
            ## Work Items
            | WI ID | WI Title | WI Type |
            | --- | ------------------------ | ----- |
            {{#forEach workItems}}
            | **[{{this.id}}]({{this._links.html.href}})** | {{lookup this.fields 'System.Title'}} | {{lookup this.fields 'System.WorkItemType'}} |
            {{/forEach}}
            {{/if}}

            {{#if (gt commits.length 0)}}
            ## Commits
            | Commit ID | Commit Message | Commited By |
            | --- | ------------------------ | ----- |
            {{#forEach commits}}
            | **[{{truncate this.id 7}}]({{this.displayUri}})** | {{remove_after_first_newline this.message}} | {{this.author.displayName}} |
            {{/forEach}}
            {{/if}}

            {{#if (gt pullRequests.length 0)}}
            ## Pull Requests
            | PR ID | PR Title | Source Branch | PR Completion Date
            | --- | ------------------------ | ------- | ------- |
            {{#forEach pullRequests}}
            | **[{{this.pullRequestId}}]({{replace (replace this.url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** | {{this.title}} | {{replace this.sourceRefName "refs/heads/" ""}} | {{date_formatter this.closedDate}} |
            {{/forEach}}
            {{/if}}
                        
            ## Metadata
            | Build ID | Build Number | Branch | Repository | Date |
            | --- | --- | ---- | ---- | ---- |
            | **[{{buildDetails.id}}]({{buildDetails._links.web.href}})** | {{buildDetails.buildNumber}} | {{replace buildDetails.sourceBranch "refs/heads/" ""}} | [{{buildDetails.repository.name}}]({{buildDetails.repository.url}}) | {{date_formatter buildDetails.startTime}} |

The issue is that this prints all the commits made inside of my mono-repository including commits that don't directly relate to my service. e.g. Looking at my repo structure, if I'm running the pipeline for basket I would only want to see commits/work items in the release notes that have been made in either src/services/basket/ or tests/services/basket/unit/

Is there a way to achieve this currently?

### Describe the solution you'd like

Potentially being able to specify a comma separated list of file paths that the tool then uses to retrieve commits/work items/pull requests that relate to only a specific service.

**Comment by rfennell** [comment] 2023-11-24 18:09
The way to approach this is to create a custom extension that does the filtering.

This [sample](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203%20(and%20later)/each_with_sort_by_field.js) filters the work items based on criteria, but you could do something similar with the commits

**Comment by faheemgani** [comment] 2023-11-28 19:43
Really appreciate you getting back to me - it has been a busy few days so has taken me a while to get my head into this...

I have managed to put some extensions together which work perfectly on my local machine (using a JSON dump of the commits, pull requests and work items for the dataset) - however - I can't seem to get it to work with the inline template I am using in the ADO task! Keep seeing this error which would suggest that I am missing a close tag? All the if's and each's have closing tags:

```
Expecting 'OPEN_INVERSE_CHAIN', 'INVERSE', 'OPEN_ENDBLOCK', got 'EOF']
```

Handlebars is new to me so I may be missing something obvious!!

Helpers.js
```
const filterPullRequests = (pullRequests, labelName) => {
    return pullRequests.filter(pullRequest => {
        return pullRequest.labels.some(label => label.name.toLowerCase() === labelName.toLowerCase());
    });
};

module.exports = {

    date_formatter(theDate) {
        return theDate.toLocaleString();
    },

    remove_after_first_newline(inputString) {
        const newlineIndex = inputString.indexOf('\n');

        if (newlineIndex !== -1) {
            return inputString.substring(0, newlineIndex);
        } else {
            return inputString;
        }
    },

    filterPullRequests(pullRequests, labelName, options) {
        //filters pull requests by label
        const filteredPullRequests = filterPullRequests(pullRequests, labelName)

        return options.fn(filteredPullRequests);
    },

    filterWorkItems(pullRequests, labelName, workItems, options) {
        
        const associatedWorkItemIds = [];

        //only return PR's with a label/tag (e.g. basket-api) 
        const filteredPullRequests = filterPullRequests(pullRequests, labelName)

        //retrieve work item id from each pullRequest in the filteredPullRequests
        filteredPullRequests.forEach(pullRequest => {
            if (pullRequest.associatedWorkitems && pullRequest.associatedWorkitems.length > 0) {
                pullRequest.associatedWorkitems.forEach(associatedWorkItem => {
                    const workItemId = associatedWorkItem.id;
                    if (workItemId) {
                        associatedWorkItemIds.push(workItemId);
                    }
                });
            }
        });

        //lookup the workItems array and return only those work items that are in the associatedWorkItemsId array
        const filteredWorkItems = workItems.filter(workItem => {
            return associatedWorkItemIds.includes(workItem.id);
        });

        return options.fn(filteredWorkItems);
    },

    filterCommitsByPaths(commits, paths, opts) {

        if(opts.data) {
            data  = handlebars.createFrame(opts.data) 
        }
        //takes a comma separated list of paths and only returns commits that were made in those paths
        paths = paths.split(',').map(path => path.replace(/\/$/, ''));

        const filteredCommits = commits.filter(commit => {
            return commit.changes.some(change => paths.includes(change.item.path));
        });

        return options.fn(filteredCommits);
    }


};
```

Task in ADO Pipeline:

```
          - task: XplatGenerateReleaseNotes@4
            displayName: 'Generate Release Notes'
            inputs:
              checkstages: true
              outputfile: '$(System.DefaultWorkingDirectory)/$(service_name)-release-notes.md'
              outputVariableName: OutputText
              customHandlebarsExtensionFile: 'helpers.js'
              customHandlebarsExtensionFolder: '$(System.DefaultWorkingDirectory)/tools/release-notes/'
              templateLocation: InLine
              inlinetemplate: |
                # Release Notes: {{buildDetails.definition.name}} 
                
                {{#filterWorkItems pullRequests "$(service_name)" workItems}}
                {{#if this.length}}
                ## Work Items
                | WI ID | WI Title | WI Type |
                | --- | ------------------------ | ----- |
                {{#each this}}
                | **[{{this.id}}]({{_links.html.href}})** | {{lookup fields 'System.Title'}} | {{lookup fields 'System.WorkItemType'}} |
                {{/each}}
                {{/if}}

                {{#filterCommitsByPaths commits "$(file_paths)"}}
                {{#if this.length}}
                ## Commits
                | Commit ID | Commit Message | Commited By |
                | --- | ------------------------ | ----- |
                {{#each this}}
                | **[{{truncate id 7}}]({{displayUri}})** | {{remove_after_first_newline message}} | {{author.displayName}} |
                {{/each}}
                {{/if}}

                {{#filterPullRequests pullRequests "$(service_name)"}}
                {{#if this.length}}
                ## Pull Requests
                | PR ID | PR Title | Source Branch | PR Completion Date
                | --- | ------------------------ | ------- | ------- |
                {{#each this}}
                | **[{{pullRequestId}}]({{replace (replace url "_apis/git/repositories" "_git") "pullRequests" "pullRequest"}})** | {{title}} | {{replace sourceRefName "refs/heads/" ""}} | {{date_formatter closedDate}} |
                {{/each}}
                {{/if}}
                        
                ## Metadata
                | Build ID | Build Number | Branch | Repository | Date |
                | --- | --- | ---- | ---- | ---- |
                | **[{{buildDetails.id}}]({{buildDetails._links.web.href}})** | {{buildDetails.buildNumber}} | {{replace buildDetails.sourceBranch "refs/heads/" ""}} | [{{buildDetails.repository.name}}]({{buildDetails.repository.url}}) | {{date_formatter buildDetails.startTime}} |

                ## All Info

                ##commits
                {{json commits}}
                        
                ##buildDetails
                {{json buildDetails}}
                        
                ##releaseDetails
                {{json releaseDetails}}
                        
                ##pullRequests
                {{json pullRequests}}
                        
                ##workItems
                {{json workItems}}
                        
                ##builds
                {{json builds}}
```

**Comment by rfennell** [comment] 2023-11-28 21:23
I think the issue is you have not closed the handlebars block

> In Handlebars, {{expression}} is used to output the value of an expression. [The expression can be a variable, a property of an object, or a more complex expression ](https://handlebarsjs.com/guide/expressions.html)[1](https://handlebarsjs.com/guide/expressions.html). The values returned by the {{expression}} are HTML-escaped by default. [If you don’t want Handlebars to escape a value, use the triple-stash {{{expression}}} instead ](https://handlebarsjs.com/guide/expressions.html)[1](https://handlebarsjs.com/guide/expressions.html).
>
> On the other hand, {{#expression}} is used to define a block expression. [A block expression is a section of a template that is conditionally rendered based on the value of the expression ](https://handlebarsjs.com/guide/expressions.html)[1](https://handlebarsjs.com/guide/expressions.html). [For example, {{#if}} is a block expression that conditionally renders a section of a template based on the value of the expression ](https://handlebarsjs.com/guide/expressions.html)[1](https://handlebarsjs.com/guide/expressions.html).

If this is the issue the fix is to add the closing block
```
{{#filterWorkItems pullRequests "label" workItems}}
{{#if this.length}}
## Work Items
| WI ID | WI Title | WI Type |
| --- | ------------------------ | ----- |
{{#each this}}
| **[{{this.id}}]({{_links.html.href}})** | {{lookup fields 'System.Title'}} | {{lookup fields 'System.WorkItemType'}} |
{{/each}}
{{/if}}
{{/filterWorkItems }}
````

**Comment by faheemgani** [comment] 2023-11-29 09:25
So I did try this yesterday as I saw that in your [example](https://github.com/rfennell/AzurePipelines/blob/main/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%203%20(and%20later)/each_with_sort_by_field.js) you had a closing tag.

When I add the closing tag in I get a different error:

```
Loaded handlebars extension file
##[error]Error Processing handlebars [ReferenceError: handlebars is not defined]
##[debug]Processed: ##vso[task.issue type=error;]Error Processing handlebars [ReferenceError: handlebars is not defined]
##[error]Error Processing handlebars [ReferenceError: handlebars is not defined]
##[debug]Processed: ##vso[task.issue type=error;]Error Processing handlebars [ReferenceError: handlebars is not defined]
```

**Closed** 2023-11-29 11:11 UTC
Labels: enhancement, GenerateReleaseNotes (XPlat version)
