### ISSUE TITLE
Generate Release Notes Task -Error The guid specified for parameter projectId must not be Guid.Empty. Parameter name: projectId

### ISSUE THREAD

**Issue by manojpaidimarri** [rfennell/AzurePipelines#694] opened 2020-04-27 21:20 UTC
[ReleaseLogs_129.zip](https://github.com/rfennell/AzurePipelines/files/4542104/ReleaseLogs_129.zip)
### Azure DevOps Extension you are using
*There are a number of Azure DevOps (VSTS) extension in this repo so please say which one you are using, and if an extension contains multiple tasks which task also*
**Generate Release Notes Task in release pipeline**
### Where are you running it?
*You can run the extensions in the cloud or on-premise*
 **Azure DevOps Service (VSTS)**

### Version of Extension/Task
Ver 2

### Expected behaviour and actual behaviour
Trying to automate release notes using **Generate Release Notes Task** and pipeline is failing with error he guid specified for parameter projectId must not be Guid.Empty. Parameter name: projectId

Attached pipeline logs

**Comment by rfennell** [comment] 2020-04-28 08:23
I have had a look at the logs and i would expect the next line after the totals to be related to Pull requests. The strange thing is the code does not contain a ProjectID.

I think the next steps are 

- for you to re-run the release but with the system.debug=true variable set so we get the detailed logging info. 
- also send me the template you are using

**Comment by manojpaidimarri** [comment] 2020-04-28 14:40
[template.txt](https://github.com/rfennell/AzurePipelines/files/4546010/template.txt)
[ReleaseLogs_131.zip](https://github.com/rfennell/AzurePipelines/files/4546012/ReleaseLogs_131.zip)

- I have created new release with system.debug=true and attached logs
- Attached template used in inline script 

Let me know if I am missing anything.

**Comment by rfennell** [comment] 2020-04-28 15:05
Ok, I think I have spotted the issue, it is a bug.  will look into it and get a new build out

**Comment by rfennell** [comment] 2020-04-28 15:46
I have just released 2.39.2, this might fix the issue, or will at least provide more debug information.

The problem is related to getting the details of the build related to the pipeline to then lookup PR information. This call is meant to infer the projectID, in your case it is failing. There is now extra logic to check for missing value and work around it.

Let me know how it goes

**Comment by manojpaidimarri** [comment] 2020-04-28 18:06
Hi Richard,

I am getting a different error now. **Cannot read property 'type' of undefined**

attached logs for your reference
[ReleaseLogs_137.zip](https://github.com/rfennell/AzurePipelines/files/4547684/ReleaseLogs_137.zip)

**Comment by rfennell** [comment] 2020-04-29 10:24
OK I think I have found the issue. The logs show

```
2020-04-28T16:41:57.5349377Z ##[debug]Build.BuildId=af4e5d0783ec57d479135344de47a0375b9d899d
2020-04-28T16:41:57.5350899Z ##[debug]Build.ProjectId=b5542b6f-97a1-4920-9eab-be5145d28f96
2020-04-28T16:41:57.5351328Z ##[debug]Getting the details of build NaN from project b5542b6f-97a1-4920-9eab-be5145d28f96
```

That the task expects the BuildID to be a number, relating to an Azure DevOps build. This original error was being masked by the handling of the ProjectID (which can be the name of the project or its GUID), by passing the projectID explicitly it exposed this real error.  

This does raise the question 'why is your build ID not a number but a GUID?'. I am assuming that the triggering artifact not an Azure DevOps build, a Git Repo ?

Anyway, the fix is the same, to put logic in to make sure I only run my logic to check for PR trigger information in the trigger artifact if it is an Azure DevOps Build

This has been releases a 2.40.1.

Let me know how it goes

**Comment by rfennell** [comment] 2020-04-29 16:14
Sorry that publish got delayed -  2.40.1 is up now

**Comment by rfennell** [comment] 2020-05-05 13:24
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Comment by rfennell** [comment] 2020-05-05 13:24
As per my standard practice I am closing this issue as I have heard nothing for a while. If this issue remains a problem please do not hesitate to re-open it

**Closed by rfennell** 2020-05-05 13:24 UTC
Labels: GenerateReleaseNotes (XPlat version), bug
