### ISSUE TITLE
support for wiki order page

### ISSUE THREAD

**Issue by renaudpaquaynsi** [rfennell/AzurePipelines#1009] opened 2021-05-16 08:49 UTC
Hello,

Now that I'm using your WIKI updater task to upload release notes created with the GenerateReleaseNotes task, I'm missing a way to update the .order page in the wiki along with committing the new files on the wiki.

The default order is alphabetical when no .order file is present in the Wiki repository
https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-file-structure?view=azure-devops#order-file

The scenario would be the following :
The name of the markdown pages in the wiki consist of : <branch_name>-<versionNumber>.md
The expected display order in the wiki would be either ascending or descending
Example : 
release-1.4.8.md
release-1.4.9.md
release-1.4.10.md
release-1.4.11.md
...

My issue is that files are appearing in the wrong order due to this alphabetical order.
Example :
release-1.4.10.md
release-1.4.11.md
release-1.4.8.md
release-1.4.9.md
...

The feature request is to have an extra parameters that would allow to decide whether uploaded file names would be inserted at the beginning or at the end of the .order file

**Comment by rfennell** [comment] 2021-05-16 14:50
This general point has been requested before. The issue is that people want different rules for the `.order` file. The recommendation previously has been to use some inline PowerShell or Bash to update the file based on the pipeline's specific needs.

That said, the feature as you suggest does seem to cover most use-cases. I will look into getting it implemented

**Comment by rfennell** [comment] 2021-05-16 20:15
This will be released in 1.25.x

There are two now parameters

- insertLinefeed - If set to true, when appending or prepending content to a page file a newline is inserted between the old and new content (See #988). Default is false
- updateOrderFile - If set to true, when appending or prepending an entry in the Azure DevOps WIKI .order file. Default is false
- prependEntryToOrderFile - If updateOrderFile is set to true, this parameter control whether the entry is appended (when this is set to false) or prepending (when this is set to true). Default is false i.e append mode

**Closed** 2021-05-16 20:31 UTC
Labels: WIKIUpdater, enhancement

**Comment by renaudpaquaynsi** [comment] 2021-05-17 06:23
Hello Richard,

That's awesome !! Thanks a lot for this super quick implementation 👍 

That said, I noticed in the code that when the updateOrderFile option is set to true and that the .order file doesn't exist in your repository, it will not throw any error nor send any warning. More than that, it seems that you will log that the entry was appended or prepended in the .order file (educated guess from reading the code).

If so, you should probably consider centralizing the fs.existsSync(orderFile) at the beginning of the method, throw an error or send a warning right the way (depending on the design choice that you want to make), and execute the ap/pre/pending afterwards. It will avoid some confusion for users.

Thanks and Regards,

Renaud

**Comment by rfennell** [comment] 2021-05-17 08:16
It is a reasonable suggestion to throw a message of some type if the `.order` file does not exist. However, from past experience, nobody ever looks at the logs unless it is an error, and I feel throwing an error when a user has to explicitly switch on the feature seems wrong.

I will add some extra logging, and updated the readme to make the new behaviour a bit clearer

**Comment by oleamu** [comment] 2022-02-03 20:28
Hello,

This wiki updater works great in my organization (thank you for the great work!), except when it comes to ordering of the files. We have a rather large folder hierarchy with Markdown files and `.order` files at various levels. Currently the wiki updater updates the `.order` file at the root to the repository. In Azure DevOps Wiki it is the `.order` file in the various folders which are used for ordering (as far as I have found out).

Would it be possible to update the `.order` file in the same folder as the Markdown file is put?

Thanks,
Ole

**Comment by rfennell** [comment] 2022-02-04 09:09
@oleamu it seems a reasonable succession. Could you create a new issue with the details requirements with some exact examples I can test against
