### ISSUE TITLE
Error:  Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by geertbleyen** [rfennell/AzurePipelines#1487] opened 2023-03-08 12:46 UTC
### Azure DevOps Extensions

Generate Release Notes (Node Cross Platform)

### Platform

Azure DevOps Server (TFS) - Specify Version

### Azure DevOps Server (TFS) Version

Azure Devops Server 2020 Update 1.2

### Extension Version

4.5.2

### Describe the bug

Yesterday the 'Generate Release Notes' extension got updated from 4.4.1 to 4.5.2 and since then, we can't generate our release notes anymore in our release pipelines, as during data gathering we get an error "Cannot read property 'length' of undefined"

I saw in the repo history that on 08/03/2023 already a commit was done that seems to be involved and possible fixes the issue, but I just want to make sure that this issue is known and can get fixed. 
If that commit indeed already fixes the issue, I'd like to gently nudge to get the Azure Devops marketplace extension version bumped as soon as possible :).

### Repo Steps

1. Create Azure Devops Server release pipeline
2. Add Generate Release Notes tast
3. Use following inline template script:
``` 
{{#each workItems}}
{{#if (eq (lookup this.fields 'System.WorkItemType') 'Bug')}}
* fixed: {{lookup this.fields 'System.Title'}}
{{/if}}
{{/each}}

{{#each workItems}}
{{#if (eq (lookup this.fields 'System.WorkItemType') 'Requirement')}}
* new: {{lookup this.fields 'System.Title'}}
{{/if}}
{{/each}}
```
4. Run pipeline

### Expected Behavior

In version 4.4.1 of the extension this yielded the desired output md file, which we could use for pushing our app the Apple's TestFlight.

### Logging Information

2023-03-08T11:34:56.3332160Z Adding [2] items
2023-03-08T11:34:56.3427220Z Checking for user defined WIQL query
2023-03-08T11:34:56.3460660Z No WIQL query parameters defined
2023-03-08T11:34:56.3467590Z Sorting WI by type then id
2023-03-08T11:34:56.3588170Z The default artifact for the release was not linked to an Azure DevOps Git Repo Pull Request
2023-03-08T11:34:56.3595600Z Getting all completed Azure DevOps Git Repo PRs in the Team Project Motion
2023-03-08T11:34:56.3597240Z Skipping getting associated PRs
2023-03-08T11:34:56.3605180Z Enriching known Pull Requests
2023-03-08T11:34:56.3616360Z Total Builds: [1]
2023-03-08T11:34:56.3639450Z Total Commits: [1]
2023-03-08T11:34:56.3644000Z Total Workitems: [2]
2023-03-08T11:34:56.3657520Z Total Related Workitems (Parent/Children): [0]
2023-03-08T11:34:56.3659200Z Total Release Tests: [0]
2023-03-08T11:34:56.3661340Z Total Tests: [0]
2023-03-08T11:34:56.3663250Z Total Manual Test Runs: [0]
2023-03-08T11:34:56.3665470Z Total Manual Test Configurations: [0]
2023-03-08T11:34:56.3670260Z Total Pull Requests: [0]
2023-03-08T11:34:56.3672290Z Total Indirect Pull Requests: [0]
2023-03-08T11:34:56.3673830Z Total Associated Test WI: [0]
2023-03-08T11:34:56.3725600Z ##[error]TypeError: Cannot read property 'length' of undefined
2023-03-08T11:34:56.3811410Z ##[error]TypeError: Cannot read property 'length' of undefined
2023-03-08T11:34:57.8590780Z ##[error]TypeError: Cannot read property 'length' of undefined

**Comment by rfennell** [comment] 2023-03-08 13:32
This is a duplicate of #1484 and has been fixed in 4.6.2.

**Closed by rfennell** 2023-03-08 13:32 UTC
Labels: bug, duplicate, GenerateReleaseNotes (XPlat version)
