### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by chakaSA** [rfennell/AzurePipelines#671] opened 2020-04-09 12:50 UTC
### Azure DevOps Extension you are using
Generate Release Notes XPlatform 

### Where are you running it?
- Azure DevOps Service (VSTS)

### Version of Extension/Task
Version: 1.9.4

### Expected behaviour and actual behaviour
Create the md file

### Steps to reproduce the problem
1. Used in release pipeline.
2. vs2017-win2016
3. Output file goes to: $(System.DefaultWorkingDirectory)\$(Release.ReleaseName).md

This was set up some time ago for one of the teams. I have not used the ext for some time so not sure where to start resolving.

Some log extract:
2020-04-09T07:31:28.9084821Z Getting work items between release [11091] and [10687]
2020-04-09T07:31:28.9088335Z Getting the workitems associated between release 11091 and release 10687
2020-04-09T07:31:29.4778165Z Work items found: 250
2020-04-09T07:31:29.4786000Z Getting the workitem details for 30194,30670,30879,31153,31225,31566,31593,31614,31621,31703,31704,31709,31739,30378,31163,31369,31398,31407,31448,31453,31454,29816,30885,30924,31061,31249,31280,31330,31366,31368,31379,31391,20755,20757,22417,22510,23156,23537,23552,23624,23625,23626,23692,23745,23746,23747,23748,23749,23752,23753,23754,23761,23810,23811,23815,23816,23818,23819,23821,23824,23851,23853,23854,23855,23859,23860,23861,23871,23873,23896,23932,23946,23956,23961,23973,24029,24050,24051,24069,24070,24071,24074,24081,24082,24087,24094,24099,24114,24122,24123,24126,24129,24131,24132,24133,24140,24168,24226,24227,24229,24275,24276,24280,24283,24285,24309,24321,24338,24341,24369,24399,24489,24490,24491,24492,24499,24509,24510,24518,25615,26493,26533,26559,26599,26607,26608,26611,26998,27001,27012,27056,27070,27132,27151,27162,27170,27173,27175,27183,27216,27220,27245,27274,27353,27354,27356,27357,27416,27429,27431,27494,29804,29808,29819,29824,29827,29833,29836,29887,29911,29912,29913,29914,29934,29935,29944,29952,29954,29970,29987,29993,29999,30013,30014,30070,30087,30088,30099,30147,30173,30175,30184,30235,30256,30266,30267,30276,30288,30318,30320,30321,30322,30323,30324,30326,30329,30330,30331,30332,30374,30421,30520,30521,30533,30554,30555,30713,30871,30923,30926,30998,31065,31097,31115,31116,31117,31121,31145,31149,31157,31164,31171,31195,31198,31214,31233,31234,31237,31239,31266,31241,31253,24519,24524,24525,24552,24555,24559,24563,24564,24568,24577,24600,24626,24664,24683,24690,24691,24692,24694
2020-04-09T07:31:29.5272810Z Getting commits between [042b002d46b3ddc183cf8267099ad1aabfc2a883] and [3f5b0062bf958a21bc5e4c9121dbf0450a9b21e0].
2020-04-09T07:31:29.5277491Z Repository type TfsGit
2020-04-09T07:31:29.5278589Z Getting the commits between commit ID 042b002d46b3ddc183cf8267099ad1aabfc2a883 and 3f5b0062bf958a21bc5e4c9121dbf0450a9b21e0 from repo b984c2a5-4be6-4dd3-836f-b8b73ca97d25
2020-04-09T07:31:29.7392526Z Commits found: 125
2020-04-09T07:31:29.7393125Z Total commits found: 125
2020-04-09T07:31:29.7393589Z Total workitems found: 1
2020-04-09T07:31:29.7399084Z Processing template
2020-04-09T07:31:29.7399755Z Processing Line: 1
2020-04-09T07:31:29.7401110Z Mode != BODY
2020-04-09T07:31:29.7403141Z Nothing to expand, just process the line
2020-04-09T07:31:29.7403589Z Processing Line: 2
2020-04-09T07:31:29.7404653Z Mode != BODY
2020-04-09T07:31:29.7405184Z Nothing to expand, just process the line
2020-04-09T07:31:29.7405582Z Processing Line: 3
2020-04-09T07:31:29.7405991Z Mode != BODY
2020-04-09T07:31:29.7406304Z Processing Line: 4
2020-04-09T07:31:29.7406662Z Mode != BODY
2020-04-09T07:31:29.7407017Z Nothing to expand, just process the line
2020-04-09T07:31:29.7409366Z Processing Line: 5
2020-04-09T07:31:29.7410361Z Mode != BODY
2020-04-09T07:31:29.7410778Z Processing Line: 6
2020-04-09T07:31:29.7411104Z Mode != BODY
2020-04-09T07:31:29.7411437Z Nothing to expand, just process the line
2020-04-09T07:31:29.7411678Z Processing Line: 7
2020-04-09T07:31:29.7411841Z Mode != BODY
2020-04-09T07:31:29.7412051Z Nothing to expand, just process the line
2020-04-09T07:31:29.7412259Z Processing Line: 8
2020-04-09T07:31:29.7412623Z Mode != BODY
2020-04-09T07:31:29.7415566Z Nothing to expand, just process the line
2020-04-09T07:31:29.7420596Z Processing Line: 9
**2020-04-09T07:31:29.7445258Z (node:7744) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'id' of undefined**
2020-04-09T07:31:29.7640840Z ##[section]Finishing: Generate Release Notes based on Release Comparision API

**Comment by rfennell** [comment] 2020-04-09 13:10
That's a very old version of the extension, it is currently at 2.33.3. There was a major re-write between 1.x and 2.x, the default template format changes slighly, there is also the option to use Handlebars as the templating language. [You can find samples for V2 here](https://github.com/rfennell/AzurePipelines/tree/master/SampleTemplates/XplatGenerateReleaseNotes%20(Node%20based)/Version%202)

So my suggestions are
- try V2 of the task
- if the problems persist can you let me see the template you are using

**Comment by chakaSA** [comment] 2020-04-09 14:05
OK thanks.
Checked and ext is already up to date to 2.33. Saw now that the task version can be changed so have set this to 2.*

Will go through the new templates and test.
Thx again

**Comment by chakaSA** [comment] 2020-04-09 18:00
Test run went through fine. Sure changes to actual pipeline will be fine as well  :)

**Comment by rfennell** [comment] 2020-04-14 08:08
Good news, I will close the issue. Re-open if the problem is not sorted

**Closed by rfennell** 2020-04-14 08:08 UTC
Labels: GenerateReleaseNotes (XPlat version)
