### ISSUE TITLE
Unable to run BuildVariableTask on a linux agent (docker / kubernetes vsts agents in aks)

### ISSUE THREAD

**Issue by DinoSourcesRex** [rfennell/AzurePipelines#455] opened 2019-03-12 15:13 UTC
### Azure DevOps Extension you are using
I am using the `BuildVariableTask` extension.

### Where are you running it?
I am running this on Azure DevOps Service (VSTS) (cloud)

### Version of Extension/Task
`1.13.11`, simply using `1.*` on the build step - I assume it's automatically updated without me having to tell AzureDevops to pull a new package down.

### Expected behaviour and actual behaviour

The actual behaviour is shown at [Build Output](#build-output). I basically get an error.

I expect the extension to function on my linux based build agents.

### Steps to reproduce the problem

The steps I have defined on AzureDevops are as follows:

1. Restore
2. Build
3. Pack
4. Increment using BuildVariableTask

It is on step 4 that I receive the error.

### Build output

```
##[section]Starting: Increment patch number for next build
==============================================================================
Task         : Set variable on a build defintion
Description  : Set variable on a build defintion
Version      : 1.13.11
Author       : Richard Fennell
Help         : Version: 1.13.11. [More Information](https://github.com/rfennell/vNextBuild/wiki/BuildTasks-Task/)
==============================================================================
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
##[section]Finishing: Increment patch number for next build
```

**Comment by rfennell** [comment] 2019-03-13 09:29
The task is written in  PowerShell so can only be run on Windows based agents. 

In the long term I plan to move this over to Node, but no immediate plans

**Comment by DinoSourcesRex** [comment] 2019-03-13 11:06
@rfennell I'm totally unfamiliar with how AzurePipeline tasks work but would it be possible to deploy a bash script as well as a powershell script side by side? And just select which one is appropriate for the OS somehow?

If that's not something that's possible / that you want to accept a PR for in the short term if you have the time to tell me what structure I am aiming for in node, and possibly an existing example task, I can give it a shot in my own time and send you a PR when it's ready.

**Comment by rfennell** [comment] 2019-03-13 11:47
I am not sure if you can run bash on a Windows build agent, never tried. The Linux  subsystem is there is it might be possible. I would just it a try, just swap the agent to a hosted Windows as opposed to Linux or OSX

As to accepting PRs, always happy to consider them, there is already a Issue #443 marked as help wanted on exactly this limitation

**Comment by DinoSourcesRex** [comment] 2019-03-13 11:49
@rfennell I'll investigate a little bit and see what I can do.

**Comment by rfennell** [comment] 2019-03-13 11:58
@DinoSourcesRex  thanks the migration process is not too bad just time consuming. You can see examples of a convert in the file utilities extensions.

**Comment by rfennell** [comment] 2019-03-14 09:59
I am closing this as it is a duplicate of #443 which already marked as help wanted

**Closed by rfennell** 2019-03-14 09:59 UTC
Labels: BuildUtilities, duplicate

**Comment by DinoSourcesRex** [comment] 2019-07-07 18:54
I have personally replaced the usage of this with a powershell script. It's not ideal but [here's](https://gist.github.com/DinoSourcesRex/48db15c50635225b970840425e46a3d1) the info for anyone who wants a similar solution.
